export const constants = {
  MENUS: [
    {
      id: 1,
      url: '/home',
      icon: '../../assets/images/menu/home-24px.svg',
      active_icon: '../../assets/images/menu-active/home-24px.svg',
      name: 'Home',
    },
    {
      id: 2,
      url: '/regional-data',
      icon: '../../assets/images/menu/folder_open-24px.svg',
      active_icon: '../../assets/images/menu-active/folder_open-24px.svg',
      name: 'Regional Data',
    },
    {
      id: 3,
      url: '/machine',
      icon: '../../assets/images/menu/noun_Scanner_2387221.svg',
      active_icon: '../../assets/images/menu-active/noun_Scanner_2387221.svg',
      name: 'Machine',
    },
    {
      id: 4,
      url: '/crop',
      icon: '../../assets/images/menu/noun_Grain_2688835.svg',
      active_icon: '../../assets/images/menu-active/noun_Grain_2688835.svg',
      name: 'Crop',
    },
    {
      id: 5,
      url: '/farmer',
      icon: '../../assets/images/menu/people_alt-24px.svg',
      active_icon: '../../assets/images/menu-active/people_alt-24px.svg',
      name: 'Farmers',
    },
  ],
  indiaState: [
    { id: 'AP', name: 'Andhra Pradesh' },
    { id: 'AR', name: 'Arunachal Pradesh' },
    { id: 'AS', name: 'Assam' },
    { id: 'BR', name: 'Bihar' },
    { id: 'CG', name: 'Chandigarh' },
    { id: 'CT', name: 'Chhattisgarh' },
    { id: 'DL', name: 'Delhi' },
    { id: 'GA', name: 'Goa' },
    { id: 'GJ', name: 'Gujarat' },
    { id: 'HR', name: 'Haryana' },
    { id: 'HP', name: 'Himachal Pradesh' },
    { id: 'JK', name: 'Jammu and Kashmir' },
    { id: 'JH', name: 'Jharkhand' },
    { id: 'KA', name: 'Karnataka' },
    { id: 'KL', name: 'Kerala' },
    { id: 'MP', name: 'Madhya Pradesh' },
    { id: 'MH', name: 'Maharashtra' },
    { id: 'MN', name: 'Manipur' },
    { id: 'ML', name: 'Meghalaya' },
    { id: 'MZ', name: 'Mizoram' },
    { id: 'NL', name: 'Nagaland' },
    { id: 'OR', name: 'Orissa' },
    { id: 'PC', name: 'Pondicherry' },
    { id: 'PB', name: 'Punjab' },
    { id: 'RJ', name: 'Rajasthan' },
    { id: 'SK', name: 'Sikkim' },
    { id: 'TN', name: 'Tamil Nadu' },
    { id: 'TR', name: 'Tripura' },
    { id: 'UP', name: 'Uttar Pradesh' },
    { id: 'UT', name: 'Uttarakhand' },
    { id: 'WB', name: 'West Bengal' },
  ],
  crops: ['Maize', 'Wheat', 'Rice', 'Barley', 'Millet'],
  machineType: ['Type 1', 'Type 2', 'Type 3', 'Type 4'],
  userType: ['Farmer','Broker','Trader','Inspector','Technician']
};